# Generated by Django 3.0.5 on 2020-04-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cardio',
            field=models.ManyToManyField(blank=True, related_name='users', to='workouts.Cardio'),
        ),
        migrations.AddField(
            model_name='user',
            name='muscle_training',
            field=models.ManyToManyField(blank=True, related_name='users', to='workouts.MuscleTraining'),
        ),
    ]
