# Generated by Django 3.0.5 on 2020-04-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_auto_20200418_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cardio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='muscle_training',
        ),
    ]
