# Generated by Django 3.0.5 on 2020-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('speed', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('muscles_worked', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=10)),
                ('duration', models.IntegerField(blank=True)),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('speed', models.IntegerField(blank=True)),
            ],
        ),
    ]
