# Generated by Django 3.0.5 on 2020-04-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='speed',
            field=models.IntegerField(null=True),
        ),
    ]
