# Generated by Django 3.0.5 on 2020-04-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20200418_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscletraining',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
