# Generated by Django 3.0.5 on 2020-04-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20200421_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muscletraining',
            name='weight',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
