# Generated by Django 3.0.5 on 2020-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_auto_20200421_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardio',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
